
name: 01b-ejercicio-hola-mundo
on:
  workflow_dispatch:
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Hola mundo
      run: echo "Hola Emiliano!"
